### ISSUE TITLE
Problem with Angular 1.4.8 

### ISSUE THREAD

**Issue by popzadid** [isteven/angular-multi-select#375]
I update my project with angular 1.4.8 and have a problem on this module 
and have some error like this
```
Error: [$rootScope:infdig] http://errors.angularjs.org/1.4.8/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22ms…itemLabel'%20)%22%2C%22newVal%22%3A%7B%7D%2C%22oldVal%22%3A%7B%7D%7D%5D%5D
    at Error (native)
    at http://localhost:1234/components/angular/angular.min.js:6:416
    at r.$digest (http://localhost:1234/components/angular/angular.min.js:131:499)
    at r.$apply (http://localhost:1234/components/angular/angular.min.js:134:78)
    at g (http://localhost:1234/components/angular/angular.min.js:87:444)
    at T (http://localhost:1234/components/angular/angular.min.js:92:50)
    at XMLHttpRequest.e (http://localhost:1234/components/angular/angular.min.js:93:129)(anonymous function) @ angular.min.js:107(anonymous function) @ angular.min.js:81r.$apply @ angular.min.js:134g @ angular.min.js:87T @ angular.min.js:92e @ angular.min.js:93
angular.min.js:6 Uncaught Error: [$rootScope:infdig] http://errors.angularjs.org/1.4.8/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22ms…itemLabel'%20)%22%2C%22newVal%22%3A%7B%7D%2C%22oldVal%22%3A%7B%7D%7D%5D%5D
```
Thank you

**Comment by isteven** [comment]
@popzadid , 

If possible, please replicate the problem in JsFiddler or Plunker. It will help me a lot. Cheers.

**Comment by miguelfrias** [comment]
I think that probably it's an error in the implementation: https://docs.angularjs.org/error/$rootScope/infdig
